[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
flate2 = "1"
hex = "0.4"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
sha1 = "0.10"
zip = { version = "2", default-features = false, features = ["deflate"] }
tempfile = "3"
pollster = "0.4"
bytemuck = { version = "1.25", features = ["derive"] }
wgpu = { version = "30.0.1", default-features = false, features = ["dx12", "gles", "std", "vulkan", "wgsl"] }

eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "glow", "x11", "wayland"] }
rfd = "0.17.2"
winit = { version = "0.30.13", default-features = false, features = ["x11", "wayland"] }

[dev-dependencies]
tempfile = "3"
